#!/usr/bin/with-contenv bash

echo "watch-files started"

# Watch for changes to cron files and update /etc/crontab/root

inotifywait -m -r /config/cron.d -e attrib,modify,move,create,delete | \
    while read -r watched_filename event_names event_filename; do
	event_path="${watched_filename}${event_filename}"
	echo "--- ${watched_filename} ${event_names} ${event_filename}: ${event_path} ---" >&2
	case "${event_path}" in
	    /config/cron.d|/config/cron.d/*)
		sed -re 's/\s+root(\s+rsnapshot\s+)/\1/' /etc/crontab.root $(find /config/cron.d -type f) > /etc/crontabs/root
		echo "root" > /etc/crontabs/cron.update
		;;
	esac
    done

echo "watch-files done"
